#!/bin/bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 497067-web-01 3.85.16.206:80 check
    server 497067-web-02 100.25.222.19:80 check
EOT

# Ensure HAProxy can be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy for changes to take effect
sudo systemctl restart haproxy
